from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path: str, old: str, new: str) -> None:
    target = ROOT / path
    text = target.read_text()
    if old not in text:
        raise SystemExit(f"Expected block not found in {path}: {old[:120]!r}")
    if text.count(old) != 1:
        raise SystemExit(f"Expected exactly one block in {path}, found {text.count(old)}")
    target.write_text(text.replace(old, new, 1))


(ROOT / 'src/editor/chainBundle.ts').write_text("""import type { Point, StitchElement } from '../types'\n\nexport type ChainBundleCount = 2 | 3 | 4\n\nexport const CHAIN_BUNDLE_COUNTS: readonly ChainBundleCount[] = [2, 3, 4]\nexport const CHAIN_BUNDLE_SPACING = 22\n\nfunction radians(degrees: number) {\n  return degrees * Math.PI / 180\n}\n\nexport function chainBundleLayout(\n  center: Point,\n  count: ChainBundleCount,\n  rotation = 0,\n  spacing = CHAIN_BUNDLE_SPACING,\n): Point[] {\n  const angle = radians(rotation)\n  const axis = { x: Math.cos(angle), y: Math.sin(angle) }\n  const middle = (count - 1) / 2\n  return Array.from({ length: count }, (_, index) => {\n    const offset = (index - middle) * spacing\n    return {\n      x: center.x + axis.x * offset,\n      y: center.y + axis.y * offset,\n    }\n  })\n}\n\nexport function createChainBundle(\n  center: Point,\n  count: ChainBundleCount,\n  rotation: number,\n  createId: () => string,\n): StitchElement[] {\n  const groupId = createId()\n  return chainBundleLayout(center, count, rotation).map((point) => ({\n    id: createId(),\n    symbolId: 'chain',\n    x: point.x,\n    y: point.y,\n    rotation,\n    visible: true,\n    locked: false,\n    groupId,\n  }))\n}\n""")

(ROOT / 'src/editor/chainBundle.test.ts').write_text("""import { describe, expect, it } from 'vitest'\nimport { semanticSelectionIds } from './selectionModel'\nimport { CHAIN_BUNDLE_SPACING, chainBundleLayout, createChainBundle } from './chainBundle'\n\ndescribe('chain bundle presets', () => {\n  it('centers the requested number of real chain stitches', () => {\n    const points = chainBundleLayout({ x: 100, y: 200 }, 3)\n    expect(points).toEqual([\n      { x: 100 - CHAIN_BUNDLE_SPACING, y: 200 },\n      { x: 100, y: 200 },\n      { x: 100 + CHAIN_BUNDLE_SPACING, y: 200 },\n    ])\n  })\n\n  it('rotates the whole chain layout around its placement center', () => {\n    const points = chainBundleLayout({ x: 10, y: 20 }, 2, 90)\n    expect(points[0].x).toBeCloseTo(10)\n    expect(points[0].y).toBeCloseTo(9)\n    expect(points[1].x).toBeCloseTo(10)\n    expect(points[1].y).toBeCloseTo(31)\n  })\n\n  it('creates ordinary chain elements in one semantic selection group', () => {\n    let serial = 0\n    const bundle = createChainBundle({ x: 0, y: 0 }, 4, 15, () => `id-${++serial}`)\n    expect(bundle).toHaveLength(4)\n    expect(bundle.every((element) => element.symbolId === 'chain')).toBe(true)\n    expect(new Set(bundle.map((element) => element.id)).size).toBe(4)\n    expect(new Set(bundle.map((element) => element.groupId)).size).toBe(1)\n    expect(bundle.every((element) => element.rotation === 15)).toBe(true)\n\n    const selected = semanticSelectionIds(bundle, [bundle[2].id])\n    expect(new Set(selected)).toEqual(new Set(bundle.map((element) => element.id)))\n  })\n})\n""")

(ROOT / 'e2e/compositeChains.e2e.ts').write_text("""import { expect, test, type Page } from '@playwright/test'\n\nasync function openEditor(page: Page) {\n  await page.goto('/Crochet-Scheme-Editor/')\n  await expect(page.getByText('Редактор схем вязания', { exact: true })).toBeVisible()\n  await expect(page.locator('.autosave-indicator')).toContainText('Автосохранено')\n}\n\nasync function canvasBox(page: Page) {\n  const box = await page.locator('svg.editor-canvas').boundingBox()\n  expect(box).not.toBeNull()\n  return box!\n}\n\ntest('places 2/3/4 chain presets as real grouped chain stitches', async ({ page }) => {\n  await openEditor(page)\n  const box = await canvasBox(page)\n  let total = 0\n\n  for (const [count, rx] of [[2, 0.34], [3, 0.5], [4, 0.68]] as const) {\n    const preset = page.locator(`.chain-bundle-button[aria-label^="${count} воздушные петли"]`)\n    await preset.click()\n    await expect(page.locator('svg.editor-canvas')).toHaveClass(/placing/)\n    await page.mouse.click(box.x + box.width * rx, box.y + box.height * 0.5)\n    total += count\n    await expect(page.locator('.stitch-element')).toHaveCount(total)\n    await expect(page.locator('.stitch-element.selected')).toHaveCount(count)\n    await expect(page.locator('.group-selection-box')).toBeVisible()\n  }\n\n  const legendRow = page.getByTestId('legend-panel').locator('.legend-used-row').filter({ hasText: 'Воздушная петля' })\n  await expect(legendRow).toBeVisible()\n  await expect(legendRow.locator('.legend-used-count')).toHaveText('9')\n\n  // Smart Place/Select must still grab an existing member instead of adding another bundle.\n  const selectedMember = page.locator('.stitch-element.selected').first()\n  const memberBox = await selectedMember.boundingBox()\n  expect(memberBox).not.toBeNull()\n  await page.mouse.click(memberBox!.x + memberBox!.width / 2, memberBox!.y + memberBox!.height / 2)\n  await expect(page.locator('.stitch-element')).toHaveCount(9)\n  await expect(page.locator('svg.editor-canvas')).toHaveClass(/selecting/)\n  await expect(page.locator('.stitch-element.selected')).toHaveCount(4)\n\n  await page.locator('.selection-quick-toolbar').getByRole('button', { name: 'Дублировать' }).click()\n  await expect(page.locator('.stitch-element')).toHaveCount(13)\n  await expect(page.locator('.stitch-element.selected')).toHaveCount(4)\n  await expect(legendRow.locator('.legend-used-count')).toHaveText('13')\n})\n""")

replace_once(
    'src/App.tsx',
    "import { backgroundImageBounds } from './editor/backgroundGeometry'\n",
    "import { backgroundImageBounds } from './editor/backgroundGeometry'\nimport { CHAIN_BUNDLE_COUNTS, chainBundleLayout, createChainBundle, type ChainBundleCount } from './editor/chainBundle'\n",
)
replace_once(
    'src/App.tsx',
    "type Tool = { type: 'select' } | { type: 'pan' } | { type: 'lasso' } | { type: 'ruler' } | { type: 'place'; symbolId: string } | { type: 'row-marker' }",
    "type Tool = { type: 'select' } | { type: 'pan' } | { type: 'lasso' } | { type: 'ruler' } | { type: 'place'; symbolId: string } | { type: 'place-chain-bundle'; count: ChainBundleCount } | { type: 'row-marker' }",
)
replace_once(
    'src/App.tsx',
    """  const updatePreview = (documentPoint: Point) => {\n    if (tool.type !== 'place') return\n    const proposed: StitchElement = {\n      id: '__preview__',\n      symbolId: tool.symbolId,\n      x: documentPoint.x,\n      y: documentPoint.y,\n      rotation: 0,\n      visible: true,\n      locked: false,\n    }\n    const solved = solveSnap(\n      proposed,\n      visibleElements,\n      guides,\n      snapping,\n      viewport,\n      snapLockRef.current,\n    )\n    snapLockRef.current = solved.candidate?.key ?? null\n    setSnapTarget(solved.candidate)\n    setPreview({ ...proposed, x: solved.x, y: solved.y, rotation: solved.rotation })\n  }\n""",
    """  const updatePreview = (documentPoint: Point) => {\n    if (tool.type !== 'place' && tool.type !== 'place-chain-bundle') return\n    const symbolId = tool.type === 'place' ? tool.symbolId : 'chain'\n    const proposed: StitchElement = {\n      id: '__preview__',\n      symbolId,\n      x: documentPoint.x,\n      y: documentPoint.y,\n      rotation: 0,\n      visible: true,\n      locked: false,\n    }\n    const solved = solveSnap(\n      proposed,\n      visibleElements,\n      guides,\n      snapping,\n      viewport,\n      snapLockRef.current,\n    )\n    snapLockRef.current = solved.candidate?.key ?? null\n    setSnapTarget(solved.candidate)\n    setPreview({ ...proposed, x: solved.x, y: solved.y, rotation: solved.rotation })\n  }\n""",
)
replace_once(
    'src/App.tsx',
    """    if (tool.type === 'place') {\n      const proposed: StitchElement = {\n        id: createId(),\n        symbolId: tool.symbolId,\n        x: point.x,\n        y: point.y,\n        rotation: 0,\n        visible: true,\n        locked: false,\n      }\n      const solved = solveSnap(\n        proposed,\n        visibleElements,\n        guides,\n        snapping,\n        viewport,\n        snapLockRef.current,\n      )\n      const placed: StitchElement = {\n        ...proposed,\n        x: solved.x,\n        y: solved.y,\n        rotation: solved.rotation,\n      }\n      commitElements([...elements, placed])\n      setSelectedIds([placed.id])\n      setSelectedGuideId(null)\n      setSelectedRowMarkerId(null)\n      const definition = SYMBOL_BY_ID.get(placed.symbolId)\n      setStatus(`${t.placed}: ${symbolName(placed.symbolId, definition?.name ?? placed.symbolId, locale)}`)\n      return\n    }\n""",
    """    if (tool.type === 'place' || tool.type === 'place-chain-bundle') {\n      const symbolId = tool.type === 'place' ? tool.symbolId : 'chain'\n      const proposed: StitchElement = {\n        id: createId(),\n        symbolId,\n        x: point.x,\n        y: point.y,\n        rotation: 0,\n        visible: true,\n        locked: false,\n      }\n      const solved = solveSnap(\n        proposed,\n        visibleElements,\n        guides,\n        snapping,\n        viewport,\n        snapLockRef.current,\n      )\n      if (tool.type === 'place-chain-bundle') {\n        const placedBundle = createChainBundle(\n          { x: solved.x, y: solved.y },\n          tool.count,\n          solved.rotation,\n          createId,\n        )\n        commitElements([...elements, ...placedBundle])\n        setSelectedIds(placedBundle.map((element) => element.id))\n        setSelectedGuideId(null)\n        setSelectedRowMarkerId(null)\n        setStatus(locale === 'ru'\n          ? `Добавлено воздушных петель: ${tool.count}`\n          : `Placed chain stitches: ${tool.count}`)\n        return\n      }\n      const placed: StitchElement = {\n        ...proposed,\n        x: solved.x,\n        y: solved.y,\n        rotation: solved.rotation,\n      }\n      commitElements([...elements, placed])\n      setSelectedIds([placed.id])\n      setSelectedGuideId(null)\n      setSelectedRowMarkerId(null)\n      const definition = SYMBOL_BY_ID.get(placed.symbolId)\n      setStatus(`${t.placed}: ${symbolName(placed.symbolId, definition?.name ?? placed.symbolId, locale)}`)\n      return\n    }\n""",
)
replace_once(
    'src/App.tsx',
    """    if (tool.type === 'place') {\n      setTool({ type: 'select' })\n      setPreview(null)\n      setSnapTarget(null)\n    }\n""",
    """    if (tool.type === 'place' || tool.type === 'place-chain-bundle') {\n      setTool({ type: 'select' })\n      setPreview(null)\n      setSnapTarget(null)\n    }\n""",
)
replace_once(
    'src/App.tsx',
    """        <section className=\"panel-section symbols-section\">\n          <div className=\"section-title-row\"><h2>{t.stitches}</h2><span className=\"muted-text\">{SYMBOLS.length}</span></div>\n          {groupedSymbols.map(([category, symbols]) => (\n""",
    """        <section className=\"panel-section symbols-section\">\n          <div className=\"section-title-row\"><h2>{t.stitches}</h2><span className=\"muted-text\">{SYMBOLS.length + CHAIN_BUNDLE_COUNTS.length}</span></div>\n          <div className=\"symbol-group chain-bundle-presets\">\n            <h3>{locale === 'ru' ? 'Цепочки' : 'Chain presets'}</h3>\n            <div className=\"symbol-grid\">\n              {CHAIN_BUNDLE_COUNTS.map((count) => {\n                const active = tool.type === 'place-chain-bundle' && tool.count === count\n                const label = locale === 'ru' ? `${count} воздушные петли` : `${count} chains`\n                const abbreviation = locale === 'ru' ? `${count} ВП` : `${count} ch`\n                const title = `${label} · ${abbreviation}`\n                return (\n                  <button\n                    className={`symbol-button chain-bundle-button ${active ? 'active' : ''}`}\n                    key={`chain-bundle-${count}`}\n                    title={title}\n                    aria-label={title}\n                    onClick={() => {\n                      if (active) {\n                        setTool({ type: 'select' })\n                        setPreview(null)\n                        setSnapTarget(null)\n                        return\n                      }\n                      setTool({ type: 'place-chain-bundle', count })\n                      clearElementSelection()\n                      setSelectedGuideId(null)\n                      setSelectedRowMarkerId(null)\n                    }}\n                  >\n                    <svg viewBox=\"-48 -20 96 40\" aria-hidden=\"true\">\n                      {chainBundleLayout({ x: 0, y: 0 }, count).map((member, index) => (\n                        <g key={index} transform={`translate(${member.x} ${member.y})`} className=\"symbol-glyph\">\n                          <SymbolGlyph symbolId=\"chain\" />\n                        </g>\n                      ))}\n                    </svg>\n                    <span>{abbreviation}</span>\n                  </button>\n                )\n              })}\n            </div>\n          </div>\n          {groupedSymbols.map(([category, symbols]) => (\n""",
)
replace_once(
    'src/App.tsx',
    "className={`editor-canvas ${pan ? 'panning' : ''} ${tool.type === 'pan' ? 'pan-tool' : tool.type === 'place' ? 'placing' : tool.type === 'lasso' ? 'lassoing' : tool.type === 'ruler' ? 'measuring' : 'selecting'}`}",
    "className={`editor-canvas ${pan ? 'panning' : ''} ${tool.type === 'pan' ? 'pan-tool' : tool.type === 'place' || tool.type === 'place-chain-bundle' ? 'placing' : tool.type === 'lasso' ? 'lassoing' : tool.type === 'ruler' ? 'measuring' : 'selecting'}`}",
)
replace_once(
    'src/App.tsx',
    """            {preview && (\n              <g transform={`translate(${preview.x} ${preview.y}) rotate(${preview.rotation})`} className=\"preview-stitch\">\n                <g className=\"symbol-glyph\"><SymbolGlyph symbolId={preview.symbolId} /></g>\n              </g>\n            )}\n""",
    """            {preview && tool.type === 'place-chain-bundle' ? (\n              <g className=\"preview-stitch preview-chain-bundle\">\n                {chainBundleLayout({ x: preview.x, y: preview.y }, tool.count, preview.rotation).map((member, index) => (\n                  <g key={index} transform={`translate(${member.x} ${member.y}) rotate(${preview.rotation})`}>\n                    <g className=\"symbol-glyph\"><SymbolGlyph symbolId=\"chain\" /></g>\n                  </g>\n                ))}\n              </g>\n            ) : preview ? (\n              <g transform={`translate(${preview.x} ${preview.y}) rotate(${preview.rotation})`} className=\"preview-stitch\">\n                <g className=\"symbol-glyph\"><SymbolGlyph symbolId={preview.symbolId} /></g>\n              </g>\n            ) : null}\n""",
)

replace_once('src/i18n.ts', "brandSubtitle: 'Векторный редактор схем · v1.20.0'", "brandSubtitle: 'Векторный редактор схем · v1.21.0'")
replace_once('src/i18n.ts', "brandSubtitle: 'Vector pattern workspace · v1.20.0'", "brandSubtitle: 'Vector pattern workspace · v1.21.0'")

replace_once(
    'README.md',
    """## v1.20.0\n\nCanvas/output usability release: background underlays can be selected directly on the canvas, moved, resized from four corners, Shift-resized with preserved aspect ratio, and rotated with a dedicated handle (Shift snaps to 15°). Rotation persists in schema v21 and is honored by SVG/print bounds. Tiled print now uses complete printable-area page frames instead of corner crop marks and includes a live page/overlap preview.\n\n""",
    """## v1.21.0\n\nComposite-chain authoring release: the palette now includes 2/3/4-chain presets. Each preset creates real Chain stitch elements in one semantic group rather than a synthetic glyph, so selection, duplication, Repeat, legend counts, future ruler counting and JSON all retain the true number of chain stitches. The presets reuse existing group semantics, so project schema remains v21.\n\n## v1.20.0\n\nCanvas/output usability release: background underlays can be selected directly on the canvas, moved, resized from four corners, Shift-resized with preserved aspect ratio, and rotated with a dedicated handle (Shift snaps to 15°). Rotation persists in schema v21 and is honored by SVG/print bounds. Tiled print now uses complete printable-area page frames instead of corner crop marks and includes a live page/overlap preview.\n\n""",
)
replace_once(
    'README.md',
    '- 44 vector crochet symbols shared by palette, canvas, Repeat preview and SVG export',
    '- 44 vector crochet symbols shared by palette, canvas, Repeat preview and SVG export, plus semantic 2/3/4-chain placement presets that materialize as real Chain stitches',
)
